version: '3.4'

services:
    django: &app
      build:
        dockerfile: docker/Dockerfile
        context: .
        args:
          - SYNC_ARGS=--without dev --sync
        target: base
      image: feeds_for_sendcloud_django:latest
      env_file:
        - ./docker/envs/.django
        - ./docker/envs/.postgres
      depends_on:
        - postgres
        - redis
      command: ["./scripts/start.sh"]
      ports:
        - "8000:8000"

    postgres:
      image: postgres:13.13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - postgres_data_backups:/backups
      env_file:
        - ./docker/envs/.postgres

    redis:
      image: redis:7.0-alpine

    celery-worker:
      <<: *app
      ports: []
      depends_on:
        - django
        - redis
      command: ["./scripts/celery.sh"]

    celery-beat:
      <<: *app
      ports: []
      depends_on:
        - django
        - redis
      restart: on-failure  # it needs sometime to get the database table from postgres
      command: ["./scripts/celery_beat.sh"]

    flower:
      <<: *app
      ports:
        - "5555:5555"
      depends_on:
        - django
        - redis
      command: ["./scripts/flower.sh"]

volumes:
  postgres_data: {}
  postgres_data_backups: {}

